
import { ResearchNode } from '@/lib/gameTypes';
import {
  FlaskConical, Zap, Cog, Coins, Flame, Beaker, Droplet, Factory, Landmark, Sparkles, Wand2, Cogs, Star, Award, Settings, Bot, ToyBrick, Diamond, BookOpen, Target, GitBranch, KeyRound, Clock, Atom, BrainCircuit, Microscope, Shield, GitPullRequest, Link
} from 'lucide-react';

export const researchNodes: ResearchNode[] = [
  {
    id: 'mana_efficiency_1',
    name: 'Mana Efficiency I',
    description: 'Increases Mana generation by 25%.',
    cost: { researchPoints: 100 },
    position: { x: 10, y: 10 },
    prerequisites: [],
    icon: Zap,
    category: 'mana',
    effect: { type: 'manaMultiplier', value: 1.25 },
  },
  {
    id: 'production_boost_1',
    name: 'Production Boost I',
    description: 'Increases all production by 20%.',
    cost: { researchPoints: 250 },
    position: { x: 14, y: 10 },
    prerequisites: ['mana_efficiency_1'],
    icon: Cog,
    category: 'production',
    effect: { type: 'allProductionMultiplier', value: 1.2 },
  },
  {
    id: 'cost_reduction_1',
    name: 'Cost Reduction I',
    description: 'Reduces all costs by 10%.',
    cost: { researchPoints: 500 },
    position: { x: 10, y: 14 },
    prerequisites: ['mana_efficiency_1'],
    icon: Coins,
    category: 'economy',
    effect: { type: 'costReductionMultiplier', value: 0.9 },
  },
  {
    id: 'click_power_1',
    name: 'Click Power I',
    description: 'Increases Mana gained from clicks by 50%.',
    cost: { researchPoints: 350 },
    position: { x: 6, y: 10 },
    prerequisites: ['mana_efficiency_1'],
    icon: Droplet,
    category: 'mana',
    effect: { type: 'manaPerClickMultiplier', value: 1.5 },
  },
  {
    id: 'essence_flux_1',
    name: 'Essence Flux I',
    description: 'Increases Essence Flux generation by 30%.',
    cost: { researchPoints: 1000 },
    position: { x: 14, y: 6 },
    prerequisites: ['production_boost_1'],
    icon: Flame,
    category: 'essence',
    effect: { type: 'essenceFluxMultiplier', value: 1.3 },
  },
  {
    id: 'research_boost_1',
    name: 'Research Boost I',
    description: 'Increases Research Point generation by 25%.',
    cost: { researchPoints: 2000 },
    position: { x: 18, y: 10 },
    prerequisites: ['production_boost_1'],
    icon: Beaker,
    category: 'research',
    effect: { type: 'researchPointsMultiplier', value: 1.25 },
  },
  {
    id: 'mana_efficiency_2',
    name: 'Mana Efficiency II',
    description: 'Increases Mana generation by 50%.',
    cost: { researchPoints: 5000 },
    position: { x: 10, y: 6 },
    prerequisites: ['mana_efficiency_1'],
    icon: Zap,
    category: 'mana',
    effect: { type: 'manaMultiplier', value: 1.5 },
  },
  {
    id: 'production_boost_2',
    name: 'Production Boost II',
    description: 'Increases all production by 35%.',
    cost: { researchPoints: 10000 },
    position: { x: 18, y: 14 },
    prerequisites: ['production_boost_1', 'research_boost_1'],
    icon: Cog,
    category: 'production',
    effect: { type: 'allProductionMultiplier', value: 1.35 },
  },
  {
    id: 'cost_reduction_2',
    name: 'Cost Reduction II',
    description: 'Reduces all costs by 15%.',
    cost: { researchPoints: 15000 },
    position: { x: 6, y: 14 },
    prerequisites: ['cost_reduction_1'],
    icon: Coins,
    category: 'economy',
    effect: { type: 'costReductionMultiplier', value: 0.85 },
  },
  {
    id: 'click_power_2',
    name: 'Click Power II',
    description: 'Increases Mana gained from clicks by 100%.',
    cost: { researchPoints: 7500 },
    position: { x: 6, y: 6 },
    prerequisites: ['click_power_1'],
    icon: Droplet,
    category: 'mana',
    effect: { type: 'manaPerClickMultiplier', value: 2 },
  },
  {
    id: 'essence_flux_2',
    name: 'Essence Flux II',
    description: 'Increases Essence Flux generation by 50%.',
    cost: { researchPoints: 25000 },
    position: { x: 14, y: 2 },
    prerequisites: ['essence_flux_1'],
    icon: Flame,
    category: 'essence',
    effect: { type: 'essenceFluxMultiplier', value: 1.5 },
  },
  {
    id: 'research_boost_2',
    name: 'Research Boost II',
    description: 'Increases Research Point generation by 50%.',
    cost: { researchPoints: 50000 },
    position: { x: 22, y: 10 },
    prerequisites: ['research_boost_1'],
    icon: Beaker,
    category: 'research',
    effect: { type: 'researchPointsMultiplier', value: 1.5 },
  },
  {
    id: 'mana_efficiency_3',
    name: 'Mana Efficiency III',
    description: 'Increases Mana generation by 75%.',
    cost: { researchPoints: 100000 },
    position: { x: 10, y: 2 },
    prerequisites: ['mana_efficiency_2'],
    icon: Zap,
    category: 'mana',
    effect: { type: 'manaMultiplier', value: 1.75 },
  },
  {
    id: 'production_boost_3',
    name: 'Production Boost III',
    description: 'Increases all production by 50%.',
    cost: { researchPoints: 250000 },
    position: { x: 22, y: 14 },
    prerequisites: ['production_boost_2'],
    icon: Cog,
    category: 'production',
    effect: { type: 'allProductionMultiplier', value: 1.5 },
  },
  {
    id: 'cost_reduction_3',
    name: 'Cost Reduction III',
    description: 'Reduces all costs by 20%.',
    cost: { researchPoints: 500000 },
    position: { x: 6, y: 18 },
    prerequisites: ['cost_reduction_2'],
    icon: Coins,
    category: 'economy',
    effect: { type: 'costReductionMultiplier', value: 0.8 },
  },
  {
    id: 'click_power_3',
    name: 'Click Power III',
    description: 'Increases Mana gained from clicks by 150%.',
    cost: { researchPoints: 200000 },
    position: { x: 6, y: 2 },
    prerequisites: ['click_power_2'],
    icon: Droplet,
    category: 'mana',
    effect: { type: 'manaPerClickMultiplier', value: 2.5 },
  },
  {
    id: 'essence_flux_3',
    name: 'Essence Flux III',
    description: 'Increases Essence Flux generation by 75%.',
    cost: { researchPoints: 750000 },
    position: { x: 18, y: 2 },
    prerequisites: ['essence_flux_2'],
    icon: Flame,
    category: 'essence',
    effect: { type: 'essenceFluxMultiplier', value: 1.75 },
  },
  {
    id: 'research_boost_3',
    name: 'Research Boost III',
    description: 'Increases Research Point generation by 75%.',
    cost: { researchPoints: 1000000 },
    position: { x: 26, y: 10 },
    prerequisites: ['research_boost_2'],
    icon: Beaker,
    category: 'research',
    effect: { type: 'researchPointsMultiplier', value: 1.75 },
  },
  {
    id: 'mana_crystal_boost',
    name: 'Mana Crystal Boost',
    description: 'Increases Mana Crystal production by 100%.',
    cost: { researchPoints: 5000 },
    position: { x: 10, y: 18 },
    prerequisites: ['cost_reduction_1'],
    icon: Target,
    category: 'specific',
    effect: { type: 'specificItemMultiplier', itemId: 'mana_crystal', value: 2 },
  },
  {
    id: 'essence_collector_boost',
    name: 'Essence Collector Boost',
    description: 'Increases Essence Collector production by 100%.',
    cost: { researchPoints: 20000 },
    position: { x: 14, y: 18 },
    prerequisites: ['mana_crystal_boost'],
    icon: Target,
    category: 'specific',
    effect: { type: 'specificItemMultiplier', itemId: 'essence_collector', value: 2 },
  },
  {
    id: 'research_lab_boost',
    name: 'Research Lab Boost',
    description: 'Increases Research Lab production by 100%.',
    cost: { researchPoints: 100000 },
    position: { x: 18, y: 18 },
    prerequisites: ['essence_collector_boost'],
    icon: Target,
    category: 'specific',
    effect: { type: 'specificItemMultiplier', itemId: 'research_lab', value: 2 },
  },
  {
    id: 'mana_well_boost',
    name: 'Mana Well Boost',
    description: 'Increases Mana Well production by 100%.',
    cost: { researchPoints: 1000000 },
    position: { x: 22, y: 18 },
    prerequisites: ['research_lab_boost'],
    icon: Target,
    category: 'specific',
    effect: { type: 'specificItemMultiplier', itemId: 'mana_well', value: 2 },
  },
  {
    id: 'workshop_gears_boost',
    name: 'Workshop Gears Boost',
    description: 'Increases Workshop Gears production by 100%.',
    cost: { researchPoints: 5000000 },
    position: { x: 26, y: 18 },
    prerequisites: ['mana_well_boost'],
    icon: Target,
    category: 'specific',
    effect: { type: 'specificItemMultiplier', itemId: 'workshop_gears', value: 2 },
  },
  {
    id: 'mana_siphon_1',
    name: 'Mana Siphon I',
    description: 'Increases Mana generation by 50% and Research Point generation by 25%.',
    cost: { researchPoints: 2500000 },
    position: { x: 22, y: 6 },
    prerequisites: ['research_boost_3', 'mana_efficiency_3'],
    icon: Wand2,
    category: 'magitech',
    effect: { type: 'multiEffect', effects: [
      { type: 'manaMultiplier', value: 1.5 },
      { type: 'researchPointsMultiplier', value: 1.25 }
    ]},
  },
  {
    id: 'essence_amplifier_1',
    name: 'Essence Amplifier I',
    description: 'Increases Essence Flux generation by 100%.',
    cost: { researchPoints: 5000000 },
    position: { x: 22, y: 2 },
    prerequisites: ['essence_flux_3', 'mana_siphon_1'],
    icon: Sparkles,
    category: 'essence',
    effect: { type: 'essenceFluxMultiplier', value: 2 },
  },
  {
    id: 'master_mechanic_1',
    name: 'Master Mechanic I',
    description: 'Increases Cogwheel Gear production by 100%.',
    cost: { researchPoints: 10000000 },
    position: { x: 14, y: 22 },
    prerequisites: ['workshop_gears_boost'],
    icon: Cogs,
    category: 'mechanical',
    effect: { type: 'specificItemMultiplier', itemId: 'workshop_gears', value: 2 },
  },
  {
    id: 'mana_siphon_2',
    name: 'Mana Siphon II',
    description: 'Increases Mana generation by 75% and Research Point generation by 50%.',
    cost: { researchPoints: 25000000 },
    position: { x: 26, y: 6 },
    prerequisites: ['mana_siphon_1'],
    icon: Wand2,
    category: 'magitech',
    effect: { type: 'multiEffect', effects: [
      { type: 'manaMultiplier', value: 1.75 },
      { type: 'researchPointsMultiplier', value: 1.5 }
    ]},
  },
  {
    id: 'essence_amplifier_2',
    name: 'Essence Amplifier II',
    description: 'Increases Essence Flux generation by 150%.',
    cost: { researchPoints: 50000000 },
    position: { x: 26, y: 2 },
    prerequisites: ['essence_amplifier_1'],
    icon: Sparkles,
    category: 'essence',
    effect: { type: 'essenceFluxMultiplier', value: 2.5 },
  },
  {
    id: 'master_mechanic_2',
    name: 'Master Mechanic II',
    description: 'Increases Cogwheel Gear production by 150%.',
    cost: { researchPoints: 100000000 },
    position: { x: 10, y: 22 },
    prerequisites: ['master_mechanic_1'],
    icon: Cogs,
    category: 'mechanical',
    effect: { type: 'specificItemMultiplier', itemId: 'workshop_gears', value: 2.5 },
  },
  {
    id: 'mana_siphon_3',
    name: 'Mana Siphon III',
    description: 'Increases Mana generation by 100% and Research Point generation by 75%.',
    cost: { researchPoints: 250000000 },
    position: { x: 30, y: 6 },
    prerequisites: ['mana_siphon_2'],
    icon: Wand2,
    category: 'magitech',
    effect: { type: 'multiEffect', effects: [
      { type: 'manaMultiplier', value: 2 },
      { type: 'researchPointsMultiplier', value: 1.75 }
    ]},
  },
  {
    id: 'essence_amplifier_3',
    name: 'Essence Amplifier III',
    description: 'Increases Essence Flux generation by 200%.',
    cost: { researchPoints: 500000000 },
    position: { x: 30, y: 2 },
    prerequisites: ['essence_amplifier_2'],
    icon: Sparkles,
    category: 'essence',
    effect: { type: 'essenceFluxMultiplier', value: 3 },
  },
  {
    id: 'master_mechanic_3',
    name: 'Master Mechanic III',
    description: 'Increases Cogwheel Gear production by 200%.',
    cost: { researchPoints: 1000000000 },
    position: { x: 6, y: 22 },
    prerequisites: ['master_mechanic_2'],
    icon: Cogs,
    category: 'mechanical',
    effect: { type: 'specificItemMultiplier', itemId: 'workshop_gears', value: 3 },
  },
  {
    id: 'research_focus_1',
    name: 'Research Focus I',
    description: 'Increases Research Point generation by 100%.',
    cost: { researchPoints: 2000000000 },
    position: { x: 30, y: 18 },
    prerequisites: ['research_boost_3', 'workshop_gears_boost'],
    icon: Microscope,
    category: 'research',
    effect: { type: 'researchPointsMultiplier', value: 2 },
  },
  {
    id: 'research_focus_2',
    name: 'Research Focus II',
    description: 'Increases Research Point generation by 150%.',
    cost: { researchPoints: 5000000000 },
    position: { x: 30, y: 22 },
    prerequisites: ['research_focus_1'],
    icon: Microscope,
    category: 'research',
    effect: { type: 'researchPointsMultiplier', value: 2.5 },
  },
  {
    id: 'research_focus_3',
    name: 'Research Focus III',
    description: 'Increases Research Point generation by 200%.',
    cost: { researchPoints: 10000000000 },
    position: { x: 26, y: 22 },
    prerequisites: ['research_focus_2'],
    icon: Microscope,
    category: 'research',
    effect: { type: 'researchPointsMultiplier', value: 3 },
  },
  {
    id: 'prestige_power_1',
    name: 'Prestige Power I',
    description: 'Increases the production bonus from prestige levels by 25%.',
    cost: { researchPoints: 1000000000 },
    position: { x: 18, y: 6 },
    prerequisites: ['essence_flux_3', 'mana_efficiency_3'],
    icon: Star,
    category: 'prestige',
    effect: { type: 'prestigeLevelBonusMultiplier', value: 1.25 },
  },
  {
    id: 'prestige_power_2',
    name: 'Prestige Power II',
    description: 'Increases the production bonus from prestige levels by 50%.',
    cost: { researchPoints: 5000000000 },
    position: { x: 22, y: 10 },
    prerequisites: ['prestige_power_1'],
    icon: Star,
    category: 'prestige',
    effect: { type: 'prestigeLevelBonusMultiplier', value: 1.5 },
  },
  {
    id: 'prestige_power_3',
    name: 'Prestige Power III',
    description: 'Increases the production bonus from prestige levels by 100%.',
    cost: { researchPoints: 20000000000 },
    position: { x: 26, y: 14 },
    prerequisites: ['prestige_power_2'],
    icon: Star,
    category: 'prestige',
    effect: { type: 'prestigeLevelBonusMultiplier', value: 2 },
  },
  {
    id: 'offline_mastery_1',
    name: 'Offline Mastery I',
    description: 'Increases offline production rate by 25%.',
    cost: { researchPoints: 500000000 },
    position: { x: 6, y: 26 },
    prerequisites: ['master_mechanic_3'],
    icon: Clock,
    category: 'utility',
    effect: { type: 'offlineProductionMultiplier', value: 1.25 },
  },
  {
    id: 'offline_mastery_2',
    name: 'Offline Mastery II',
    description: 'Increases offline production rate by 50%.',
    cost: { researchPoints: 2500000000 },
    position: { x: 10, y: 26 },
    prerequisites: ['offline_mastery_1'],
    icon: Clock,
    category: 'utility',
    effect: { type: 'offlineProductionMultiplier', value: 1.5 },
  },
  {
    id: 'offline_mastery_3',
    name: 'Offline Mastery III',
    description: 'Increases offline production rate by 100%.',
    cost: { researchPoints: 10000000000 },
    position: { x: 14, y: 26 },
    prerequisites: ['offline_mastery_2'],
    icon: Clock,
    category: 'utility',
    effect: { type: 'offlineProductionMultiplier', value: 2 },
  },
  {
    id: 'golem_mastery_1',
    name: 'Golem Mastery I',
    description: 'Increases the effectiveness of all Golems by 25%.',
    cost: { researchPoints: 1500000000 },
    position: { x: 18, y: 26 },
    prerequisites: ['research_focus_3'],
    icon: Bot,
    category: 'golemancy',
    effect: { type: 'golemEffectMultiplier', value: 1.25 },
  },
  {
    id: 'golem_mastery_2',
    name: 'Golem Mastery II',
    description: 'Increases the effectiveness of all Golems by 50%.',
    cost: { researchPoints: 7500000000 },
    position: { x: 22, y: 26 },
    prerequisites: ['golem_mastery_1'],
    icon: Bot,
    category: 'golemancy',
    effect: { type: 'golemEffectMultiplier', value: 1.5 },
  },
  {
    id: 'golem_mastery_3',
    name: 'Golem Mastery III',
    description: 'Increases the effectiveness of all Golems by 100%.',
    cost: { researchPoints: 30000000000 },
    position: { x: 26, y: 26 },
    prerequisites: ['golem_mastery_2'],
    icon: Bot,
    category: 'golemancy',
    effect: { type: 'golemEffectMultiplier', value: 2 },
  },
  {
    id: 'synergy_mastery_1',
    name: 'Synergy Mastery I',
    description: 'Allows one additional Golem to be active at once.',
    cost: { researchPoints: 15000000000 },
    position: { x: 30, y: 26 },
    prerequisites: ['golem_mastery_3'],
    icon: GitPullRequest,
    category: 'golemancy',
    effect: { type: 'additionalActiveGolems', value: 1 },
  },
  {
    id: 'synergy_mastery_2',
    name: 'Synergy Mastery II',
    description: 'Allows one additional Golem to be active at once.',
    cost: { researchPoints: 50000000000 },
    position: { x: 34, y: 22 },
    prerequisites: ['synergy_mastery_1'],
    icon: GitPullRequest,
    category: 'golemancy',
    effect: { type: 'additionalActiveGolems', value: 1 },
  },
  {
    id: 'aether_channeling',
    name: 'Aether Channeling',
    description: 'Increases the production bonus from Aether Shards by 50%.',
    cost: { researchPoints: 25000000000 },
    position: { x: 22, y: 14 },
    prerequisites: ['prestige_power_2'],
    icon: Diamond,
    category: 'aether',
    effect: { type: 'aetherShardBonusMultiplier', value: 1.5 },
  },
  {
    id: 'ancient_knowledge',
    name: 'Ancient Knowledge',
    description: 'Increases the production bonus from Ancient Knowledge by 50%.',
    cost: { researchPoints: 40000000000 },
    position: { x: 18, y: 14 },
    prerequisites: ['prestige_power_2'],
    icon: BookOpen,
    category: 'knowledge',
    effect: { type: 'ancientKnowledgeBonusMultiplier', value: 1.5 },
  },
  {
    id: 'aetheric_attunement',
    name: 'Aetheric Attunement',
    description: 'Aether Shards provide a 100% stronger bonus to production.',
    cost: { researchPoints: 7.5e10 },
    position: { x: 26, y: 16 },
    prerequisites: ['aether_channeling'],
    icon: Diamond,
    category: 'aether',
    effect: { type: 'prestigeBonusMultiplier', target: 'aetherShards', value: 2 },
  },
  {
    id: 'ultimate_synergy',
    name: 'Ultimate Synergy',
    description: 'Increases the effectiveness of all Golem Synergies by 50%.',
    cost: { researchPoints: 5e10 },
    position: { x: 30, y: 10 },
    prerequisites: ['synergy_mastery_1', 'synergy_mastery_2'],
    icon: Link,
    category: 'golemancy',
    effect: { type: 'synergyEffectMultiplier', value: 1.5 },
  },
  {
    id: 'singularity_catalyst',
    name: 'Singularity Catalyst',
    description: 'Each prestige level beyond 10 provides a 2% multiplicative bonus to all production.',
    cost: { researchPoints: 1e11 },
    position: { x: 30, y: 14 },
    prerequisites: ['prestige_power_3', 'aetheric_attunement'],
    icon: Atom,
    category: 'prestige',
    effect: { type: 'singularityBonus', value: 0.02 },
  },
  {
    id: 'temporal_distortion',
    name: 'Temporal Distortion',
    description: 'Increases offline progress speed by 50% and allows it to bypass the 7-day cap.',
    cost: { researchPoints: 1.5e11, essenceFlux: 5e9 },
    position: { x: 18, y: 22 },
    prerequisites: ['offline_mastery_3'],
    icon: Clock,
    category: 'magitech',
    effect: { type: 'offlineSpeedBoost', value: 1.5 },
  },
  {
    id: 'quantum_entanglement',
    name: 'Quantum Entanglement',
    description: '1% of Mana generation is added to Research Point generation.',
    cost: { researchPoints: 2e11, essenceFlux: 1e10 },
    position: { x: 22, y: 22 },
    prerequisites: ['mana_siphon_3', 'research_focus_3'],
    icon: BrainCircuit,
    category: 'magitech',
    effect: { type: 'manaToResearchConversion', value: 0.01 },
  },
  {
    id: 'chronos_cog',
    name: 'The Chronos Cog',
    description: 'Unlocks a final, powerful upgrade for the Clockwork Automaton.',
    cost: { researchPoints: 5e11, cogwheelGears: 1e12 },
    position: { x: 12, y: 22 },
    prerequisites: ['master_mechanic_3', 'temporal_distortion'],
    icon: KeyRound,
    category: 'mechanical',
    effect: { type: 'unlockItemUpgrade', itemId: 'clockwork_automaton', upgradeId: 'final_automaton_upgrade' },
  },
];

export const researchNodeMap = new Map(researchNodes.map(node => [node.id, node]));
